# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57fa94a675b113a7f928463ed2b071f51d58dfbc2e9216f7ba9e2433695d30df7dc376f96ebc3be614c1b092705b8d18751924c478e42ebfc5788a2ceb09e57a

test:
  secret_key_base: 4942f5ca4a8d0234302d35c07cc790fe2ebe5e63d5ce1d920ec7d71dbc2e012f0ceea5c28d048c39e60e25bbd66443794d9d652a5e6ed7a7a71586671e0369af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
